version: '3.8'
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: rice_market_pgadmin
    environment:
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PYTHONPATH: /pgadmin4
    ports:
    - 5050:80
    volumes:
    - pgadmin_data:/var/lib/pgadmin
    restart: 'no'
    networks:
    - rice_market_network
  adminer:
    image: adminer:latest
    container_name: rice_market_adminer
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: postgres
      PHPIZE_DEPS: "autoconf \t\tdpkg-dev dpkg \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev\
        \ \t\tmake \t\tpkgconf \t\tre2c"
      PHP_INI_DIR: /usr/local/etc/php
      PHP_CFLAGS: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
      PHP_CPPFLAGS: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
      PHP_LDFLAGS: -Wl,-O1 -pie
      GPG_KEYS: AFD8691FDAEDF03BDF6E460563F15A9B715376CA 9D7F99A0CB8F05C8A6958D6256A97AF7600A39A6
        0616E93D95AF471243E26761770426E17EBBB3DD
      PHP_VERSION: 8.4.13
      PHP_URL: https://www.php.net/distributions/php-8.4.13.tar.xz
      PHP_ASC_URL: https://www.php.net/distributions/php-8.4.13.tar.xz.asc
      PHP_SHA256: b4f27adf30bcf262eacf93c78250dd811980f20f3b90d79a3dc11248681842df
      ADMINER_VERSION: 5.4.0
      ADMINER_DOWNLOAD_SHA256: 7a572ddc4e512d4752902b769ebb400465583d814c9d280c0b7175d51a3159e0
      ADMINER_SRC_DOWNLOAD_SHA256: 1bb363516dc674fed3d7f3823437d9a4ecbbbfca0615612fc3a8a04fe184ae9d
    ports:
    - 8081:8080
    restart: 'no'
    networks:
    - rice_market_network
  postgres:
    image: postgres:15-alpine
    container_name: rice_market_postgres
    environment:
      POSTGRES_DB: rice_market_db
      POSTGRES_INITDB_ARGS: --encoding=UTF8 --locale=en_US.utf8
      POSTGRES_MAX_CONNECTIONS: '100'
      POSTGRES_SHARED_BUFFERS: 256MB
      POSTGRES_USER: rice_admin
      POSTGRES_PASSWORD: localdev123
    ports:
    - 5433:5432
    volumes:
    - ./data-pipeline/schema/postgresql_ddl.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
    - postgres_data:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
      -c log_statement=all -c log_duration=on
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U rice_admin -d rice_market_db
      interval: 10s
      timeout: 5s
      retries: 5
    restart: 'no'
    networks:
    - rice_market_network
  redis:
    image: redis:7-alpine
    container_name: rice_market_redis
    environment:
      REDIS_VERSION: 7.4.5
      REDIS_DOWNLOAD_URL: http://download.redis.io/releases/redis-7.4.5.tar.gz
      REDIS_DOWNLOAD_SHA: 00bb280528f5d7934bec8ab309b8125088c209131e10609cb1563b91365633bb
    ports:
    - 6380:6379
    volumes:
    - redis_data:/data
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 10s
      timeout: 5s
      retries: 5
    restart: 'no'
    networks:
    - rice_market_network
networks:
  rice_market_network:
    driver: bridge
volumes:
  pgadmin_data:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local
